name: Publish Artifact to npm

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Config GIT
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Install Deps
        run: npm ci

      - name: Publish
        run: |
          npm version patch
          npm publish --access public
          git push origin master
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
