name: Publish Artifact to npm

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish to npm
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm ci
          npm version patch
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
